### ISSUE TITLE
wsvpn client's flag "--ca-certificates" works even if the specified certificate is not a signing CA certificate.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#10]
Hi Mark,

I've tested your new WSVPN 1.2.0.  

If I specify the signing CA certificate "ca.crt" for the client's ca-certificates flag, it works as expected.

However, if I copy the same server identity certificate server.crt (used on the WSVPN server) to the WSVPN client and set it to the client's ca-certificates flag, the certificate validation also seems to work.  It should only work if the matching ca.crt is specified.

CLIENT

sudo ./wsvpn_client_arm --auth-file htpasswd --proxy http://192.168.1.1:8080  --connect wss://192.168.100.1:8444
2022/06/11 14:12:18 Connecting to wss://192.168.100.1:8444 as user test
2022/06/11 14:12:18 Using HTTP proxy http://192.168.1.1:8080 
panic: x509: certificate signed by unknown authority                    <---- No matching signing CA certificate in the local CA truststore.
goroutine 1 [running]:
main.main()
	/home/runner/work/wsvpn/wsvpn/client/main.go:138 +0xc38

sudo ./wsvpn_client_arm --auth-file htpasswd --proxy http://192.168.1.1:8080 --ca-certificates ./server.crt --connect wss://192.168.100.1:8444
2022/06/11 13:58:13 Connecting to wss://192.168.100.1:8444 as user test
2022/06/11 13:58:13 Using HTTP proxy http://192.168.1.1:8080
2022/06/11 13:58:14 Network mode TUN, subnet 192.168.3.2/24, mtu 1280
2022/06/11 13:58:14 Opened tun0
2022/06/11 13:58:14 Configured interface, starting operations            <--  Working even with server.crt

SERVER
./wsvpn_server_arm --authenticator htpasswd --listen 0.0.0.0:8444 --tls-cert ./server.crt -tls-key ./server.key

CERTIFICATE INFO

server.crt:
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication   <===== Not a signing CA certificate
            X509v3 Key Usage: 
                Digital Signature, Key Encipherment

ca.crt:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Key Usage: 
                Certificate Sign, CRL Sign

**Comment by Doridian** [comment]
So, from my knowledge about TLS, this is the correct behavior.
The way TLS verification works, the server checks every certificate in the chain, and if it "knows" that certificate.
The constraints or key usage only come into play if it is ACTUALLY is used for signature, which would break the chain.

As the direct cert the server presented is already known (in the trust store), and valid for the usage (Server authentication), it is accepted.

If you don't want this behavior, simply don't add leaf certificates to the trust store.

**Comment by vochong** [comment]
WSVPN is bug-free.  Simply amazing.  Much appreciated!
