### ISSUE TITLE
Add ability to specify custom headers

### ISSUE THREAD

**Issue by kanwairen123** [Doridian/wsvpn#108]
I wonder how to specific a custom request header,  say if I want to connect to server with a different hostname header? Thank you.

**Comment by Doridian** [comment]
@kanwairen123 Currently, there is no way to send custom headers without modifying the code.

If what you want to modify the Host header for is is to connect to a certain host/IP, but verify a TLS cert for another host, that is possible via the `client` `tls` `server-name` option.

**Comment by Doridian** [comment]
Alright, shouldn't be too hard to add. I labelled this issue as a feature request, probably will get to it this week or weekend.
