### ISSUE TITLE
Performance benchmark

### ISSUE THREAD

**Issue by bt-worm** [Doridian/wsvpn#116]
Hi, Doridian, thank you for this great work!

just wonder have you ever made a performance testing of WSVPN, compared with main stream VPN solution like openvpn, etc.

and what's your suggested configuration with balance between performance and security

**Comment by Doridian** [comment]
So far I have not done any benchmarking at all, really. I'll keep this ticket open as a reminder to do that.

As for "Balance between performance and security", well. That is quite easy: Enable TLS, and use any form of authentication (either mTLS, user/password or both). Authentication does not affect performance beyond new clients connecting at all.

As TLS does its best to utilize crypto acceleration features, it should (ideally) choose the fastest way to encrypt all by itself.

For performance, I would advise getting WebTransport as the protocol going, as WebSocket faces the same problems that OpenVPN TCP does (TCP is just not an optimal protocol for a VPN tunnel) by fact of also using TCP. WebTransport, on the other hand, uses UDP.

So my suggested configuration is:
- Enable TLS, and leave TLS verification enabled (don't add the `insecure` config option)
- Enable authentication in your preferred way
- Enable WebTransport (the server will still support WebSocket if you enable WebTransport)

**Comment by bt-worm** [comment]
Great! that's clear. and I'm really expecting the performance of WebTransport. :)
