### ISSUE TITLE
Enhancement request: print the negotiated TLS cipher in the output of the WSVPN client when connecting via wss.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#12]
For example:

2022/06/12 07:18:23 Connecting to wss://somewhere:8444 as user test
2022/06/12 07:18:23 TLS cipher for data channel:  'xxxxxxxxxxxxxxxxx'              <===
2022/06/12 07:18:23 Network mode TUN, subnet 192.168.3.3/24, mtu 1460
2022/06/12 07:18:23 Opened tun0
2022/06/12 07:18:23 Configured interface, starting operations

**Comment by Doridian** [comment]
Done, prints version and cipher
