### ISSUE TITLE
[Question]WSVPN HTTP3/QUIC can't pass Clouflare CDN?

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#134]
CF and WSVPN already enable HTTP3 support.Firewall opened tcp and udp 443 both.curl -i my website show already support http3,like this below:
`alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400`
But when I use `webtransport://myweb.eu.org:443` show this: ` Client error: timeout: no recent network activity`.

**TEST**
1. Direct connect  to original IP with webtransport(quic) --- ✔
2. Direct connect to original IP with websocket(wss) --- ✔
3. Behind CF CDN with websocket(wss) --- ✔
4. Behind CF CDN with webtransport(quic) --- ❌

So what cased this issue?Thx.

**Comment by Doridian** [comment]
@Handsome1080P WebTransport uses HTTP/3 as its base, but, like WebSocket, requires explicit support for any CDN/proxy (see how CF has a "WebSocket" toggle on every domain, for example; it is a separate but related feature). From my cursory research, it seems that CloudFlare does not yet support WebTransport forwarding.

**Comment by Handsome1080P** [comment]
> @Handsome1080P WebTransport uses HTTP/3 as its base, but, like WebSocket, requires explicit support for any CDN/proxy (see how CF has a "WebSocket" toggle on every domain, for example; it is a separate but related feature). From my cursory research, it seems that CloudFlare does not yet support WebTransport forwarding.

Thx for your reply.In fact, I successfully connected once yesterday, but failed the second time.Now fullly can't connected.I checked the the CF works with h3-27, h3-28 and h3-29.Like I post above.Behind CF CDN,curl my site shows http3 support.

**Comment by Doridian** [comment]
From the error you get, you actually do get a successful connection (`no network activity` is part of the actual WebTransport code to my knowledge). Likely CloudFlare just terminates the connection because they think it is unnecessary (as they prepare for a request and a response, not a permanent tunnel).
Sometimes you can fix this by continuously passing traffic both directions (like leaving a `ping` running forever on both ends), sometimes this just needs to wait on CloudFlare to add official support.

**Comment by Handsome1080P** [comment]
> From the error you get, you actually do get a successful connection (`no network activity` is part of the actual WebTransport code to my knowledge). Likely CloudFlare just terminates the connection because they think it is unnecessary (as they prepare for a request and a response, not a permanent tunnel). Sometimes you can fix this by continuously passing traffic both directions (like leaving a `ping` running forever on both ends), sometimes this just needs to wait on CloudFlare to add official support.

Thx.I think I found the answer.
[https://community.cloudflare.com/t/unable-to-forward-webtransport-request-via-loadbalancer-to-origin/335218/3](url)

> If you’re proxying HTTP/3 (Layer 7( via the Cloudflare edge, then WebTransport won’t currently work because it is not a supported feature. WebTransport requires a SETTINGS_ENABLE_WEBTRANSPORT setting to be advertised by client and server ([WebTransport over HTTP/3 12](https://www.ietf.org/archive/id/draft-ietf-webtrans-http3-02.html#section-3.1)), which is not advertised by Cloudflare.
