### ISSUE TITLE
network unreachable via socks5 proxy server

### ISSUE THREAD

**Issue by w22gb8** [Doridian/wsvpn#146]

**Comment by Doridian** [comment]
@w22gb8 Can you share your config? Or error messages?

**Comment by w22gb8** [comment]
> @w22gb8 Can you share your config? Or error messages?

default config

server:
  listen: 127.0.0.1:9000

client:
  server: "ws://127.0.0.1:9000" 
  proxy: "socks5://xxxx:xxx"

**Comment by Doridian** [comment]
@w22gb8 I have just tested it with a SOCKS proxy and it works just fine for me tunneling through that. Can you provide log outputs from client and server?

**Comment by w22gb8** [comment]
> 

i'm sorry, I use other socks5 test is also work，But using [naive](https://github.com/klzgrad/naiveproxy) doesn't work.

server log:
```
/wsvpn -mode server -config s.yml 
2023/02/08 12:01:17 Local version is: dev (protocol 12)
2023/02/08 12:01:17 listener.go:91: [SERVER-2ba62566-72e9-4dfe-9c6c-787e95a12a1b] VPN server online at 127.0.0.1:9000 (HTTP/3 disabled, TLS disabled, mTLS disabled), Mode TUN, Subnet 192.168.3.0/24 (253 max clients), MTU 1420
2023/02/08 12:01:39 sockets.go:51: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Unencrypted connection established
2023/02/08 12:01:39 sockets.go:94: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Upgraded connection to WebSocket
2023/02/08 12:01:39 sockets.go:122: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Command serialization: json
2023/02/08 12:01:39 sockets.go:259: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Connection fully established
2023/02/08 12:01:39 commands.go:62: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Remote version is: dev (protocol 12)
2023/02/08 12:01:39 base.go:169: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Setting fragmentation: enabled
2023/02/08 12:01:39 commands.go:82: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Got reply to command ID 0576b036-d981-4af7-97d3-dc2f88de1bd5 (ok): OK
2023/02/08 12:02:04 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
2023/02/08 12:02:04 ping.go:13: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Received pong
2023/02/08 12:02:29 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
2023/02/08 12:02:29 ping.go:13: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Received pong
2023/02/08 12:02:54 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
```
client:
```
./wsvpn -mode client -config c.yml
2023/02/08 12:01:38 Local version is: dev (protocol 12)
2023/02/08 12:01:38 base.go:99: [CLIENT-UNSET] WARNING: Connecting to ws://127.0.0.1:9000 with authentications: NONE
2023/02/08 12:01:39 connection.go:55: [CLIENT-UNSET] Command serialization: json
2023/02/08 12:01:39 connection.go:61: [CLIENT-UNSET] Unencrypted WebSocket connection established
2023/02/08 12:01:39 commands.go:82: [CLIENT-UNSET] Got reply to command ID 1037e950-3c55-48f5-8130-eb5308793b3b (ok): OK
2023/02/08 12:01:39 commands.go:67: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Network mode TUN, Subnet 192.168.3.2/24, MTU 1420, IPConfig enabled
2023/02/08 12:01:39 commands.go:85: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Opened interface tun0
2023/02/08 12:01:39 commands.go:109: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Configured interface, VPN online
2023/02/08 12:02:04 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
2023/02/08 12:02:04 ping.go:13: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Received pong
2023/02/08 12:02:29 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
2023/02/08 12:02:29 ping.go:13: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Received pong
2023/02/08 12:02:54 ping.go:37: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Sent ping
2023/02/08 12:02:54 ping.go:13: [CLIENT-05f31578-b05b-415b-837d-46c5cf5a84b2] Received pong
```
client ping server:
```
ping 192.168.3.1
PING 192.168.3.1 (192.168.3.1) 56(84) bytes of data.
^C
--- 192.168.3.1 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5108ms
```

**Comment by Doridian** [comment]
@w22gb8 The fact that the tunnel seems to work, pings seem to work, but actual ICMP pings fall apart for you is really odd. I'll have to try that specific proxy and see if it has the same issues for me.

**Comment by Doridian** [comment]
@w22gb8 I cannot even get a connection working at all through naiveproxy. I think the fact it goes through a HTTP proxy that actually looks at the HTTP data (by nature of being a HTTP proxy) it screws up the WebSockets somehow.

**Comment by w22gb8** [comment]
> @w22gb8 I cannot even get a connection working at all through naiveproxy. I think the fact it goes through a HTTP proxy that actually looks at the HTTP data (by nature of being a HTTP proxy) it screws up the WebSockets somehow.

Oh,Thank you for your time.

**Comment by w22gb8** [comment]
[v5.21.0](https://github.com/Doridian/wsvpn/releases/tag/v5.21.0) works fine, later versions don't work.
client v5.24.0 and server v5.21.0 also works fine.

**Comment by Doridian** [comment]
@w22gb8 thanks for that info. That helps a lot. It is probably the new WebSocket library in that case. I'll see if I can get it to work.
So if I read you right it is only the client that breaks it, latest server works?

**Comment by w22gb8** [comment]
> @w22gb8 thanks for that info. That helps a lot. It is probably the new WebSocket library in that case. I'll see how I can get it to work. So if I read you right it is only the client that breaks it, latest server works?

yes, client v5.24.0 and server v5.21.0 don't work.

**Comment by Doridian** [comment]
After poking some more around with naive, I finally got it to work. But now it works for me even with v5.24.0, with the exact configuration you provided.
I will investigate further to see if I can find a way to figure out the differences between the WS libraries.

**Comment by w22gb8** [comment]
> After poking some more around with naive, I finally got it to work. But now it works for me even with v5.24.0, with the exact configuration you provided. I will investigate further to see if I can find a way to figure out the differences between the WS libraries.

Oh that's good, thanks.

**Comment by Doridian** [comment]
@w22gb8 Once 5.25 has finished building, that one should fix your issues!
