### ISSUE TITLE
wsvpn server 1.5.1 keeps failing when wsvpn client 1.5.1 tries to connect to it

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#15]
Wsvpn server 1.5.1 keeps failing when wsvpn client 1.5.1 tries to connect to it.  Here's the error on the server:

2022/06/14 13:11:49 [0] Error reading packet from WS: websocket: close 1006 (abnormal closure): unexpected EOF

However, if the wsvpn server is replaced with the version 1.4.0 while keeping the wsvpn client 1.5.1, it works.

CLIENT 1.5.1

> wsvpn_client_arm_1.5.1 --auth-file $HTPASSWD --proxy http://$PROXY_SERVER:$PROXY_PORT \
>                                     --tls-cipher-preference CHACHA --tls-min-version 1.3 \
>                                     --ping-interval $PING_INTERVAL --ping-timeout $PING_TIMEOUT \
>                                     --ca-certificates $CA_CERT --connect wss://$WSVPN_SERVER_IP:$WSVPN_SERVER_PORT

2022/06/14 13:11:48 Connecting to wss://something:8443 as user bitso
2022/06/14 13:11:48 Using HTTP proxy http://somewhere:8080
2022/06/14 13:11:49 TLS 1.3 connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
2022/06/14 13:11:49 [0] Ping enabled with interval 24h0m0s and timeout 10s
2022/06/14 13:11:49 [0] Error reading packet from WS: websocket: close 1006 (abnormal closure): unexpected EOF

SERVER 1.5.1

>  wsvpn_server_arm --authenticator htpasswd --listen 0.0.0.0:8443 --mtu 1460 \
>                                --tls-cipher-preference CHACHA --tls-min-version 1.3 \
>                                --ping-interval $PING_INTERVAL --ping-timeout $PING_TIMEOUT \
>                                --tls-cert $SERVER_CERT --tls-key $SERVER_KEY

2022/06/14 20:09:55 [S] VPN server online at 0.0.0.0:8443, mode TUN, serving subnet 192.168.3.0/24 (253 max clients) with MTU 1460

2022/06/14 20:11:49 http: panic serving somewhere:19955: unaligned 64-bit atomic operation
goroutine 6 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:1825 +0xec
panic({0x29a588, 0x33484c})
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:844 +0x2ac
runtime/internal/atomic.panicUnaligned()
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0x20a6f2c, 0x1)
	/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/Doridian/wsvpn/shared.(*Socket).SendCommand(0x20a6f00, {0x2ca85e, 0x4}, {0x20c3c8c, 0x3, 0x3})
	/home/runner/work/wsvpn/wsvpn/shared/socketHandler.go:106 +0x34
main.serveWs({0x335fec, 0x20aa1e0}, 0x208e480)
	/home/runner/work/wsvpn/wsvpn/server/main.go:252 +0x804
net/http.HandlerFunc.ServeHTTP(0x2e4adc, {0x335fec, 0x20aa1e0}, 0x208e480)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2084 +0x34
net/http.(*ServeMux).ServeHTTP(0x4a7ec8, {0x335fec, 0x20aa1e0}, 0x208e480)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2462 +0x164
net/http.serverHandler.ServeHTTP({0x20923f0}, {0x335fec, 0x20aa1e0}, 0x208e480)
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:2916 +0x408
net/http.(*conn).serve(0x2182060, {0x336110, 0x20ca4b0})
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:1966 +0x654
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.18.3/x64/src/net/http/server.go:3071 +0x4e0

**Comment by Doridian** [comment]
Pushed 1.5.2 to fix the bug caused by an inconsistency in go on ARM 32-bit
See: https://pkg.go.dev/sync/atomic#pkg-note-BUG
`On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned. `

**Comment by vochong** [comment]
WSVPN 1.5.2 works great.  Awesome!
