### ISSUE TITLE
Android compatibility

### ISSUE THREAD

**Issue by Doridian** [Doridian/wsvpn#158]

**Comment by NNdroid** [comment]
I have developed an Android client app that can be downloaded by following this link: [Google Play](https://play.google.com/store/apps/details?id=app.fjj.webtunnel) Feel free to give it a try!

**Comment by Alberto115x** [comment]
> I have developed an Android client app that can be downloaded by following this link: [Google Play](https://play.google.com/store/apps/details?id=app.fjj.webtunnel) Feel free to give it a try!

Will you open source the app?
