### ISSUE TITLE
Enhancement request: show build version for WSVPN client and server

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#16]
Please add the --version flag for both wsvpn client/server, or just print the version when showing the flag usage.

For example:

./wsvpn_client_amd64
Version 1.5.2                                   <===
Usage of ./wsvpn_client_amd64:
  -auth-file string
  ...

**Comment by Doridian** [comment]
Done, it also sends it to the other end now, along with a protocol version constant.
Can possibly be used in the future if back-compat is ever necessary.
