### ISSUE TITLE
[Question] How to use TAP mode in linux?

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#160]
my local lan network is 192.168.100.0/24
my server addr is 192.168.100.253/32
my gateway addr is 192.168.100.254/32
So,how to set in WSVPN?
I already set the mode to TAP,need I set subnet?

**Comment by Handsome1080P** [comment]
config file below:

> tunnel:
    mtu: 1420
    subnet: 192.168.100.0/24
    mode: TAP
    allow-client-to-client: true
    allow-ip-spoofing: false
    allow-mac-changing: true
    allowed-macs-per-connection: 1
    allow-unknown-ether-types: false
    features:
        fragmentation: true
        datagram_id_0: true
    ip-config:
        local: true
        remote: true
    ping:
        interval: 25s
        timeout: 5s
interface:
    name: "tap1"
    persist: false
    one-interface-per-connection: false

**Comment by Doridian** [comment]
@Handsome1080P Subnet is what is used to assign IPs from for the server and clients. So you need to set it to a subnet that you don't already use. Alternatively, you disable `local` and `remote` `ip-config` and attach the VPN interface to a bridge, allowing something like DHCP to configure it

**Comment by Handsome1080P** [comment]
> 

New configrations below:

> tunnel:
    mtu: 1420
    subnet: 172.16.0.0/24
    mode: TAP
    allow-client-to-client: true
    allow-ip-spoofing: false
    allow-mac-changing: true
    allowed-macs-per-connection: 1
    allow-unknown-ether-types: false
    features:
        fragmentation: true
        datagram_id_0: true
    ip-config:
        local: false
        remote: false
    ping:
        interval: 25s
        timeout: 5s
interface:
    name: "tap1"
    persist: false
    one-interface-per-connection: false

**Comment by Handsome1080P** [comment]
> 
My DHCP server is my server's gateway: 192.168.100.254 and my server's IP is 192.168.100.253.
I tryed these below:

1. use none used subnet,like 172.16.0.0/24,ip-config all true.
2. use the same net range with my lan network: 192.168.100.0/24. ip-config all false.

And got this result:

1. Server interface get IP: 172.16.0.1 and client get IP 172.16.0.2.Try use dhcpcd get second ip from client interface,failed.
2. Server interface get IP: 192.168.100.1 and client no ip set.Ty use dhcpcd get new IP from client interface,failed.

Wsvpn how to set the bridge to my physical interfaces?

**Comment by Doridian** [comment]
@Handsome1080P You have to add it via, say `brctl addif br0 tap0` (whichever is your bridge and the server interface). You can try automating that with an up script in the config.

**Comment by Handsome1080P** [comment]
> @Handsome1080P You have to add it via, say `brctl addif br0 tap0` (whichever is your bridge and the server interface). You can try automating that with an up script in the config.

Thx,I will try latter

**Comment by Handsome1080P** [comment]
> @Handsome1080P You have to add it via, say `brctl addif br0 tap0` (whichever is your bridge and the server interface). You can try automating that with an up script in the config.

I set `IP-Config` all false at server side and use another ip range be subnet.
Client still can't get IP from server's uplink DHCP.Client use `dhclient vpn0`  get IP fail.

Server Config:
![image.png](https://s2.loli.net/2023/02/19/PnwXR6T1aOoiYkN.png)

Server Bridge Info:
![image.png](https://s2.loli.net/2023/02/19/TFSgq1efWiAMP2o.png)

Server Interfaces Info:
![image.png](https://s2.loli.net/2023/02/19/wnfpa3ZJz9QSY7T.png)
![image.png](https://s2.loli.net/2023/02/19/NhmHMLXptJKeEP6.png)

Client Config:
![image.png](https://s2.loli.net/2023/02/19/rNktA36zdeYp5ul.png)

Client Interfaces Info:
![image.png](https://s2.loli.net/2023/02/19/gjVnCtYrfwsJkTm.png)

**Comment by Handsome1080P** [comment]
Server log:
![image.png](https://s2.loli.net/2023/02/19/4e3G2Lw6tRU7VB8.png)

**Comment by Doridian** [comment]
@Handsome1080P Could you also provide logs from the server's DHCP server and the client's DHCP client, so I could maybe see what part it gets stuck on?

**Comment by Handsome1080P** [comment]
> @Handsome1080P Could you also provide logs from the server's DHCP server and the client's DHCP client, so I could maybe see what part it gets stuck on?

DHCP just a simple router,no any DHCP logs about new client try to get IPs.Client I can post some logs latter.Before I try get IP with dhclient just  stuck no any output.

**Comment by Handsome1080P** [comment]
> > @Handsome1080P Could you also provide logs from the server's DHCP server and the client's DHCP client, so I could maybe see what part it gets stuck on?
> 
> DHCP just a simple router,no any DHCP logs about new client try to get IPs.Client I can post some logs latter.Before I try get IP with dhclient just stuck no any output.

And I can sure my bridge no issues.Bcz my 2 containers all are using DHCP get IPs.VPN logs show sent and received Ping/Pong, working fine.

**Comment by Doridian** [comment]
@Handsome1080P Try enabling `allow-ip-spoofing`. That will be required anyway once DHCP is working (since a DHCP assigned IP is not visible to WSVPN at the moment). However, it might also fix the initial DHCP broadcast packets (as in, DHCPDISCOVER packets).

**Comment by Handsome1080P** [comment]
> 

OK,I will try later.Thx

**Comment by Handsome1080P** [comment]
`allow-ip-spoofing` = true
Client request IP,but server no response.
![image.png](https://s2.loli.net/2023/02/20/dqkM4VFiwu3NjKz.png)

**Comment by Handsome1080P** [comment]
The guys who need TAP mode,follow this steps below:

1. Use a not used IP range be the subnet.
2. Enable `allow-ip-spoofing` in configration file at server side.
3. Disable `ip-config` all options in configration file at server side.
4. Add the TAP interface to your bridge or bond somethinga by  `brctl`.
5. At client side,use dhcp client get IP from your VPN interface.

**Comment by Handsome1080P** [comment]
or like this,not need brctl.Create tap first and add it to bridge.Then enable `persist: true` and disable `one-interface-per-connection: false`
![image.png](https://s2.loli.net/2023/02/21/lvdb6S9qx7jTyC3.png)
![image.png](https://s2.loli.net/2023/02/21/Iai7Pqy2vwV6Ctu.png)
