### ISSUE TITLE
[Question] How to add post-up scripts?

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#164]
I try to add a post-up scripts.But I don't know how to add it.I checked the default config and help info.But not working.

> scripts:
    up: ["/usr/local/etc/wsvpn/up.sh"]
    down: []

up.sh

> #!/bin/bash
/usr/bin/brctl addif br0 tap0

**Comment by Doridian** [comment]
@Handsome1080P Keep in mind: `up` scripts are called when a client connects, not when the interface gets created if you use a single-interface server.
If all you want is to add the tap interface to a bridge, the easiest way to do such might be to use whatever way your Linux distro has to add "hot-pluggable" interfaces to a bridge. (Alternatively, if you use a singular interface for the VPN, just add it to the bridge with a 5 second delay after starting WSVPN)

**Comment by Doridian** [comment]
Also, I have just posted the v5.27.0 release, which adds a `startup` script to the server. This should be able to accomplish what you wanted.

**Comment by Handsome1080P** [comment]
> Also, I have just posted the v5.27.0 release, which adds a `startup` script to the server. This should be able to accomplish what you wanted.

post-start?I will test latter.

**Comment by Handsome1080P** [comment]
> Also, I have just posted the v5.27.0 release, which adds a `startup` script to the server. This should be able to accomplish what you wanted.

It's working.thx.

> scripts:
    up: []
    down: []
    startup: ["/usr/local/etc/wsvpn/up.sh"]
