### ISSUE TITLE
[Question] [Resolved]Client how to set MAC Address

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#166]
I am using TAP mode and get IP from DHCP pool.So I wanna bind my mac with a IP.At client side can set static IP or use post-up script to change interface's mac address?Or create a same name interface first and give it a mac address.

**Comment by Doridian** [comment]
@Handsome1080P You can create the interface manually first and use `persist: true` and set a fixed name so that WSVPN re-uses the pre-made interface.

**Comment by Handsome1080P** [comment]
> 
thx.
what will  `persist:true` changed in my system?If interfaces created by vpn itself?

**Comment by Doridian** [comment]
@Handsome1080P `persist: true` instructs WSVPN to use  pre-existing interfaces with the same name (as the name you gave) and to not delete the interface after it exits (as in, to leave it around for re-use)

**Comment by Handsome1080P** [comment]
@Doridian 
If it created itself,the interface's config will write to my `interface` files(Debian)?

**Comment by Doridian** [comment]
@Handsome1080P Correct, you can do that if you use `persist: true`

**Comment by Handsome1080P** [comment]
@Doridian Thx,I will try.

**Comment by Handsome1080P** [comment]
@Doridian I have tested,after reboot,the interface won't write to my system configration.But is doesnt matter,I just need the vpn use pre-existing interface.So I can delete server side's post-up script.Created a TAP interface and add it to bridge first.Server is Archlinux,it is ez to do this.

**Comment by Doridian** [comment]
@Handsome1080P with `persist: true` the server WILL use a pre-existing interface (or create its own if it does not already exist, so make sure the OS creates it before you start the WSVPN server). Also you need to make sure `one-interface-per-connection` is `false` (otherwise WSVPN will have to dynamically create interfaces on the server side)

**Comment by Handsome1080P** [comment]
@Doridian yeah,`one-interface-per-connection` of course is false.I not need it.Thx.

**Comment by Handsome1080P** [comment]
Server side also can create tap and add it to bridge.Then enable `persist: true` and disable `one-interface-per-connection: false`
![image.png](https://s2.loli.net/2023/02/21/lvdb6S9qx7jTyC3.png)
![image.png](https://s2.loli.net/2023/02/21/Iai7Pqy2vwV6Ctu.png)
