### ISSUE TITLE
[Bug]VPN Restart Failled If 'persist:true''

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#167]
For test,I set name to `tap1` ,then set` persist:true`,let the VPN create interface by itself.
Start once,then exit,interface and local IP not removed.Then start VPN fail.Error log below:
Server Config:

> interface:
    name: "tap1"
    persist: true
    one-interface-per-connection: false

Interface Info:
![image](https://user-images.githubusercontent.com/13675031/220339974-2630784a-16cd-4592-a7ba-97eb9469325c.png)

Error Log:
![image](https://user-images.githubusercontent.com/13675031/220340122-999b6df9-828c-4603-a984-b1f58d92a2b3.png)

**Comment by Doridian** [comment]
Fixed in v5.28.0

**Comment by Handsome1080P** [comment]
> Fixed in v5.28.0

thx
