### ISSUE TITLE
Typo error "Authebnticator" in the description of the server flag -authenticator-config

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#18]
./server-linux-amd64 -h
WSVPN version 1.7.0
Usage of ./server-linux-amd64:
  -authenticator string
    	Which authenticator to use (allow-all, htpasswd) (default "allow-all")
  -authenticator-config string
    	Authebnticator config file (ex. htpasswd file for htpasswd authenticator, empty for default)

**Comment by Doridian** [comment]
Oops, fixed
