### ISSUE TITLE
Add ability to specify naming pattern for tun interfaces (such as wsvpn# etc)

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#19]
I have several different tun interfaces on the server, e.g. tun0 for openvpn.  For wsvpn,  it does not allow me to specify a fix tun interface, and may create and bind to either tun1, or tun2, or tun3 etc.  if the server is rebooted and the startup script starts wsvpn server.   Since I use zone-based firewall,  this change of tun interface affects the firewall zoning.

**Comment by Doridian** [comment]
@vochong In `tun` mode (the default, you can change that with `--tap`) the server has to create a new interface for every connections, those are point-to-point interfaces.
If you run the server n TAP mode, where all clients share one interface, you can use `--tap-name` to use a fixed/constant name.

**Comment by vochong** [comment]
Is it possible for force wsvpn server to always start a new tun interface at the lowest possible number?.   E.g. if tun0 is being used, start with tun1 and so on.

**Comment by Doridian** [comment]
@vochong It will use whatever number the OS decides on. To make it choose different names (which I might add in the future) I would have to add logic to be able to determine which interfaces already exist, which I do not have right now.

**Comment by Doridian** [comment]
You can now set the interface name to use on the client (`--interface-name`) as well as the naming pattern/prefix to use for TUN interfaces on Linux (`--tun-naming-prefix`). If you specify a custom prefix it will always use the lowest available number.

If you want to firewall, you can now either explicitly specify `prefix0` if you expect to only have a single client,
Or, alternatively, you can use the wildcard features the Linux firewall has and specify `prefix+`.
For example: `iptables -A INPUT -i wsvpn+ -j ACCEPT`

**Comment by vochong** [comment]
Thanks a lot Mark.  You're super quick!
