### ISSUE TITLE
Please support forward proxy for wsvpn client.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#2]
Hello,

Please add HTTP proxy support for wsvpn client.  It will make it work in virtually any network environment.  Thanks a lot.

**Comment by Doridian** [comment]
@vochong So what you mean is the client connects through an HTTP proxy you can configure to the server? If so, I can add that sure.

**Comment by vochong** [comment]
Hi Doridian,

Yes, please add HTTP proxy support so that wsvpn client can traverse it in order to reach the wsvpn server.  Many networks only provide HTTP proxy for users to access the Internet.   Thanks a lot.

**Comment by Doridian** [comment]
https://github.com/Doridian/wsvpn/releases/tag/1.0.9 This release adds HTTP proxy support in the client via the `proxy` argument.
