### ISSUE TITLE
Win 11 Default gateway not work.

### ISSUE THREAD

**Issue by Onair-santa** [Doridian/wsvpn#203]
Work only ping-pong
In 5.30 internet work with default IP and interface, vpn not work
In 5.32 Internet crash.
Client.yml
 set-default-gateway: true
  ping:
    interval: 30s
    timeout: 5s
client:
  server: "ws://..........:9000"

**Comment by Doridian** [comment]
If I understand you correctly, your internet stops working with `set-default-gateway`?

Make sure you have a dedicated route set for your VPN endpoint (via `route ADD ...`). Most other VPNs will automatically add a route for the VPN server to avoid this, WSVPN does not have this feature, yet.

For example, if your VPN server is 1.2.3.4 and your router is 192.168.1.1, you would use (in an administrator command prompt):
```
route add 1.2.3.4 MASK 255.255.255.255 192.168.1.1
```

**Comment by Onair-santa** [comment]
Not work with routing and route add
Internet crash and only ping-pong.
OK Thnx. Project is good. May be in next release
