### ISSUE TITLE
Client Disconnect when in a heavy traffic

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#204]
Log:
![Untitled.png](https://s2.loli.net/2023/04/12/YICz1bxtOZ7g9B5.png)

**Comment by Doridian** [comment]
@Handsome1080P
1) Are you using WebSocket or WebTransport? It looks like WebSocket from the `tcp` error
2) Can you share logs from the server as well? Those are probably necessary to figure this one out

**Comment by Handsome1080P** [comment]
> @Handsome1080P
> 
> 1. Are you using WebSocket or WebTransport? It looks like WebSocket from the `tcp` error
> 2. Can you share logs from the server as well? Those are probably necessary to figure this one out

Thx for the reply.I add reconnect 1s to client side, issue solved.

**Comment by Handsome1080P** [comment]
> @Handsome1080P
> 
>     1. Are you using WebSocket or WebTransport? It looks like WebSocket from the `tcp` error
> 
>     2. Can you share logs from the server as well? Those are probably necessary to figure this one out

Server log below.


![图片.png](https://s2.loli.net/2023/04/13/g5pRiVGjDfMBs49.png)

**Comment by Doridian** [comment]
Must be a concurrency issue, so far I couldn't reproduce it, but I'll keep trying. (I have a "benchmarking" setup with VMs to try and push as much traffic as possible)

**Comment by Handsome1080P** [comment]
> Must be a concurrency issue, so far I couldn't reproduce it, but I'll keep trying. (I have a "benchmarking" setup with VMs to try and push as much traffic as possible)

thx.

**Comment by Doridian** [comment]
Can not reproduce this at all
