### ISSUE TITLE
None of the mips images can run on cpu model: MIPS 74Kc V5.0

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#23]
Hi Mark,

Is there any additional MIPS arch that the go compiler can handle?   I've tried all the mips images but none of them seems to work on the following platform (it's supposed to be 32-bits only, but I also ran 64-bits images for reference):

https://openwrt.org/docs/techref/instructionset/mipsel_74kc

system type		: Qualcomm Atheros QCA9558 ver 1 rev 0
machine			: TP-Link Archer C7 v2
processor		: 0
cpu model		: MIPS 74Kc V5.0
BogoMIPS		: 359.42
wait instruction	: yes
microsecond timers	: yes
tlb_entries		: 32
extra interrupt vector	: yes
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0ffb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2
ASEs implemented	: mips16 dsp dsp2
Options implemented	: tlb 4kex 4k_cache prefetch mcheck ejtag llsc dc_aliases perf_cntr_intr_bit
 cdmm contextconfig perf
shadow register sets	: 1
kscratch registers	: 0
package			: 0
core			: 0
VCED exceptions		: not available
VCEI exceptions		: not available

 ./server-linux-mips -h
Illegal instruction

./server-linux-mipsle -h
./server-linux-mipsle: line 1: syntax error: unexpected "("

./server-linux-mips64 -h
./server-linux-mips64: line 1: syntax error: unexpected ")"

./server-linux-mips64le -h
./server-linux-mips64le: line 1: syntax error: unterminated quoted string

**Comment by Doridian** [comment]
Try `server-linux-mips-softfloat` I just added in 1.12.1, I suspect that CPU just doesn't have a floating point unit.

**Comment by vochong** [comment]
It works great.   Thank you very much.
