### ISSUE TITLE
Enhancement request: add the ability to save the command line settings in a config file.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#24]
When you have some time, please add the ability for wsvpn client and wsvpn server to invoke a config file with the command line settings in it, since there are lots of possible command line settings to set.   Doing so would also help prevent other users from seeing the name/location of the htpasswd, certificate, private key files etc when doing "ps".   Thanks a lot.

**Comment by Doridian** [comment]
Sounds good. Might change all the CLI arguments to a config file instead and just a single `--config-file=` or similar option.
Then I can provide example files and make everything much easier to handle.

**Comment by Doridian** [comment]
Started work on config files:
TODO:
[ ] Validation of config files
[ ] Sane defaults for unspecified options

**Comment by Doridian** [comment]
3.0.0 now uses config files, will release 3.1.0 with the above TODOs fixed soon

**Comment by Doridian** [comment]
Defaults added in 3.1.0 (same defaults as the command line flags used to have)
