### ISSUE TITLE
mTLS configuration issue

### ISSUE THREAD

**Issue by limbo127** [Doridian/wsvpn#246]
Hello, 
i'm trying to configure mTLS without success. I'm using cfssl with an helper as : https://github.com/mradile/cfssl-mtls-demo/blob/main/Makefile

All certificats seems to be good but log from server show : 
wsvpn   --mode server --config server.yml
2023/06/06 21:38:30 listener.go:98: [SERVER-947865ef-2edd-4b6b-8721-9b054f016436] VPN server online at :9000 (HTTP/3 enabled, TLS enabled, **mTLS disabled**), Mode TUN, Subnet 192.168.3.0/24 (253 max clients), MTU 1420
          
[nicolas@ouis test]$ cat server.yml 
tunnel:
    subnet: 192.168.3.0/24

server:
    listen: ":9000"
    enable-http3: true # Specify this if you want to use WebTransport as well
    tls:
        key: "certs/server-key.pem" # Filename of a PEM formatted private key
        certificate: "certs/server.pem" # Filename of a PEM formatted certificate (with chain if applicable)
        client-ca: "certs/ca.pem" # Filename of the CA that signed all client certificates

Nicolas

**Comment by Doridian** [comment]
This is a display issue only, fixed in https://github.com/Doridian/wsvpn/pull/247

mTLS is actually enabled, the logs just incorrectly say it is not.
