### ISSUE TITLE
Some questions regarding the latest version 3.2.0

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#25]
Regarding 3.2.0:

1) What is component-id?    It seems that there is a duplicate description for tun and tap interfaces in the client default config:

interface:
  tap:
    name: ""
    persist: false
    component-id: root\tap0901 # Defaults: root\tap0901 or tap0901    <====
  tun:
    name: ""
    component-id: root\tap0901 # Defaults: root\tap0901 or tap0901     <====

2) Can I still use "auth-file" for the client yaml, e.g.   Can you please add it to the example client config.

Thanks a lot.

./wsvpn_client_arm --print-default-config
tunnel:
  set-default-gateway: false
  ping:
    interval: 30s
    timeout: 5s

interface:
  tap:
    name: ""
    persist: false
    component-id: root\tap0901 # Defaults: root\tap0901 or tap0901
  tun:
    name: ""
    component-id: root\tap0901 # Defaults: root\tap0901 or tap0901              

scripts:
  # These scripts get run as "script operation subnet interface"
  # Example: "./handler.sh up 192.168.3.2/24 tun0"
  up: ""
  down: ""

client:
  server: "" # Examples: ws://example.com:9000 wss://secure.example.com:9000
  proxy: "" # Example: http://user:password@proxy.example.com:8080
  tls:
    ca: "" # Filename of CA bundle for verifying server cert
    certificate: "" # Filename of certificate for mTLS
    key: "" # Filename of private key for mTLS
    config:
      insecure: false
      min-version: 1.2
      max-version: 1.3
      cipher-preference: "" # blank, AES or CHACHA

**Comment by Doridian** [comment]
`component-id` is a Windows-only option for people who have multiple TUN/TAP interfaces on Windows, since the Windows TUN/TAP driver works differently from Linux/macOS

`auth-file` still exists, but I forgot to document it. That has been fixed.

**Comment by Doridian** [comment]
As for the duplication: As the server decides if a VPN is TUN or TAP, I wanted clients to have the ability to configure the naming scheme (and other options) differently, depending on which type the VPN uses.
