### ISSUE TITLE
Client output to show Websocket or WebTransport 

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#27]
I enable WebTransport support (enable-http3) on the wsvpn server.  When the client connects to the wsvpn server, it does not show WebTransport connection.  Can you please add an additional log message indicating whether the finally negotiated transport is Websocket or WebTransport.  Thanks a lot.

2022/07/08 07:29:34 Local version is: 3.4.0 (protocol 7)
2022/07/08 07:29:34 base.go:76: [CLIENT-UNSET] Connecting to wss://x.x.x.x:xxxx with authentications: mTLS, HTTP
2022/07/08 07:29:36 connection.go:55: [CLIENT-UNSET] Command serialization: json
2022/07/08 07:29:36 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebSocket connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
2022/07/08 07:29:36 ping.go:48: [CLIENT-UNSET] Ping enabled with interval 1h0m0s and timeout 5s
2022/07/08 07:29:36 commands.go:60: [CLIENT-UNSET] Remote version is: 3.4.0 (protocol 7)
2022/07/08 07:29:36 commands.go:73: [CLIENT-UNSET] Got reply to command ID 9e4e7c09-21b8-4504-88ad-f35bcaf38030 (ok): OK
2022/07/08 07:29:36 commands.go:58: [CLIENT-1aa60733-dc8a-4113-9281-80e4c03414e6] Network mode TUN, Subnet 10.10.11.3/24, MTU 1472, IPConfig enabled
2022/07/08 07:29:36 commands.go:74: [CLIENT-1aa60733-dc8a-4113-9281-80e4c03414e6] Opened wsclient
2022/07/08 07:29:36 commands.go:87: [CLIENT-1aa60733-dc8a-4113-9281-80e4c03414e6] Configured interface, starting operations

**Comment by Doridian** [comment]
```
2022/07/08 07:29:36 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebSocket connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
```
See above, it would show "WebTransport" instead of "WebSocket" after "TLS 1.x".

Keep in mind WebTransport requires the URL to be "webtransport://server:port" (as opposed to "ws://server:port" or "wss://server:port"). There is no seperate suffix for secure WebTransport as HTTP/3 requires TLS, so it is always secure.

**Comment by vochong** [comment]
Thanks Mark.

If WebTransport is UDP-based,  can I assume that the client would not be able to traverse HTTP proxy that supports the CONNECT command (which works for WebSocket)?

**Comment by Doridian** [comment]
Correct, the client will display an error message if you attempt to use WebTransport while a proxy is set.

**Comment by vochong** [comment]
I've just tried to connect the client (Linux/Intel) to server (r7800/armv7) using WebTransport.   The connection is established but it seems that traffic cannot pass (pinging server tunnel IP). The MTU is set to 1280 and there is no HTTP proxy in between.

2022/07/08 07:57:30 Local version is: 3.4.0 (protocol 7)
2022/07/08 07:57:30 base.go:76: [CLIENT-UNSET] Connecting to webtransport://192.168.1.1:8443 with authentications: mTLS, HTTP
2022/07/08 07:57:31 connection.go:55: [CLIENT-UNSET] Command serialization: json
2022/07/08 07:57:31 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebTransport connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
2022/07/08 07:57:31 ping.go:48: [CLIENT-UNSET] Ping enabled with interval 1h0m0s and timeout 5s
2022/07/08 07:57:31 commands.go:60: [CLIENT-UNSET] Remote version is: 3.4.0 (protocol 7)
2022/07/08 07:57:31 commands.go:73: [CLIENT-UNSET] Got reply to command ID 8d22e536-5446-4cdb-80be-1b34a82c4e4b (ok): OK
2022/07/08 07:57:31 commands.go:58: [CLIENT-54aa47cc-1533-4d9c-879b-881147024ad2] Network mode TUN, Subnet 10.10.11.2/24, MTU 1280, IPConfig enabled
2022/07/08 07:57:31 commands.go:74: [CLIENT-54aa47cc-1533-4d9c-879b-881147024ad2] Opened wsclient
2022/07/08 07:57:31 commands.go:87: [CLIENT-54aa47cc-1533-4d9c-879b-881147024ad2] Configured interface, starting operations

**Comment by vochong** [comment]
I've killed the server process running in the background and run it in foreground.   When the client connects to it via WebTransport, the server shows "Error sending data message: message too large".

SERVER
2022/07/08 15:12:12 Local version is: 3.4.0 (protocol 7)
2022/07/08 15:12:12 listener.go:98: [SERVER-80d90f5a-06a5-413b-ac3f-7fd749fc02b2] VPN server online at 0.0.0.0:8443 (HTTP/3 enabled, TLS enabled, mTLS enabled), Mode TUN, Subnet 10.10.11.0/24 (253 max clients), MTU 1280
2022/07/08 15:12:17 sockets.go:45: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] TLS 1.3 connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
2022/07/08 15:12:17 sockets.go:93: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Upgraded connection to WebTransport
2022/07/08 15:12:17 sockets.go:125: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Assigned interface wstun0
2022/07/08 15:12:17 sockets.go:134: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Command serialization: json
2022/07/08 15:12:17 sockets.go:155: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Connection fully established
2022/07/08 15:12:17 ping.go:48: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Ping enabled with interval 1h0m0s and timeout 5s
2022/07/08 15:12:17 commands.go:60: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Remote version is: 3.4.0 (protocol 7)
2022/07/08 15:12:17 commands.go:73: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Got reply to command ID 032decae-4854-4a80-a161-752b3dc34848 (ok): OK
2022/07/08 15:12:17 commands.go:73: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Got reply to command ID 339d32ba-c795-4f04-994a-1abbc3cc76ab (ok): OK
2022/07/08 15:12:19 data_message.go:27: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Error sending data message: message too large


CLIENT
2022/07/08 08:12:15 Local version is: 3.4.0 (protocol 7)
2022/07/08 08:12:15 base.go:76: [CLIENT-UNSET] Connecting to webtransport://192.168.1.1:8443 with authentications: mTLS, HTTP
2022/07/08 08:12:17 connection.go:55: [CLIENT-UNSET] Command serialization: json
2022/07/08 08:12:17 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebTransport connection established with cipher=TLS_CHACHA20_POLY1305_SHA256
2022/07/08 08:12:17 ping.go:48: [CLIENT-UNSET] Ping enabled with interval 1h0m0s and timeout 5s
2022/07/08 08:12:17 commands.go:60: [CLIENT-UNSET] Remote version is: 3.4.0 (protocol 7)
2022/07/08 08:12:17 commands.go:73: [CLIENT-UNSET] Got reply to command ID b23a028f-ac18-4110-a0f0-1dd7957fd9a7 (ok): OK
2022/07/08 08:12:17 commands.go:58: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Network mode TUN, Subnet 10.10.11.2/24, MTU 1280, IPConfig enabled
2022/07/08 08:12:17 commands.go:74: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Opened wsclient
2022/07/08 08:12:17 commands.go:87: [CLIENT-0dad0609-a8c0-499c-a04d-724bfd95bfda] Configured interface, starting operations

**Comment by Doridian** [comment]
That means you might have something quite low MTU in your network (say, an LTE or DSL connection).
For now you'll have to keep lowering MTU until it fits. Below 1280, sadly any form of IPv6 will stop working, but IPv4 will be fine at lower MTUs.
Sadly, the current WebTransport library does also not give me any indication for maximum message sizing, so the only thing I could do is react to getting this error by lowering MTU, which is not ideal.
Alternatively, implement my own fragmentation protocol, but, that would again hit the problem that the library doesn't tell me how large I can go.

**Comment by vochong** [comment]
I'm connecting to the server via WIFI (over LAN), so MTU 1280 should be fine.

**Comment by Doridian** [comment]
After checking the code of quic-go itself, it seems on a normal MTU connection, the maximum payload size is 1220 for QUIC datagrams (it seems, because the code is complex, so I don't know how true this is).
Then HTTP/3 adds a couple bytes overhead for the stream ID to that.
So you'd arrive at something around 1210 max MTU for the tunnel.
See: https://github.com/lucas-clemente/quic-go/blob/master/internal/protocol/params.go#L137
I cannot tell you why it works for me at 1280, it clearly should not, might have to do with the fact my LAN uses 9000 MTU jumbo packets (but this library seems completely oblivious to the actual MTU and always default to 1220)

**Comment by vochong** [comment]
After trials and errors, I have found that the very max MTU for WebTransport is 1216 bytes (in my Ethernet and WIFI network, both with MTU 1500).

Can you please add some ping logic on the client to make sure it can ping the server tunnel IP prior to declaring that the VPN connection is up and running.  Otherwise, the client may show all good log messages but the server is actually having problem (for this server/WebTransport problem).

**Comment by Doridian** [comment]
@vochong The server should kick out the client on such a transmission fault, or at least propagate an error to the client.
The fact the client does not get any notification of the server having issues transmitting is the bug here.
I will check why the error does not get sent to the client through control commands as it should.

**Comment by Doridian** [comment]
@vochong Added a fix for the client not exiting in WebTransport settings. Next I will add a packet to actually send errors to the client. Tracking under #28
