### ISSUE TITLE
Add support for basic HTTP authentication in wsvpn server

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#3]
The existing release binaries don't have authentication support that you added later.  Thanks a lot.

**Comment by Doridian** [comment]
The authentication support I added does not actually do anything on its own. It is simply an interface for people to implement a way to add authentication to the server if they so choose.

So a new compile is not going to do much, unless actual authentication code is added (I always run this server behind nginx, which I use for authentication instead)

**Comment by vochong** [comment]
For the wsvpn client,  I could specify the option -auth-file ./myauthfile,  but I don't see a similar option for the wsvpn server.  Can you please explain its usage?  Thanks a lot.

./client-linux-arm64 -h
Usage of ./client-linux-arm64:
  -auth-file string
    	File to read authentication from in the format user:password
  -connect string
    	Server address to connect to (default "ws://example.com")
  -default-gateway
    	Route all traffic through VPN
  -down-script string
    	Script to run when the VPN goes offline
  -up-script string
    	Script to run once the VPN is online


./server-linux-amd64  -h
Usage of ./server-linux-amd64:
  -client-to-client
    	Allow client-to-client communication (in TAP)
  -listen string
    	Listen address for the WebSocket interface (default "127.0.0.1:9000")
  -mtu int
    	MTU for the tunnel (default 1280)
  -subnet string
    	Subnet for the tunnel clients (default "192.168.3.0/24")
  -tap
    	Use a TAP and not a TUN
  -tap-iface-noconf
    	Do not configure TAP interface at all except MTU
  -tap-name string
    	Use specific TAP name
  -tap-no-ifconfig
    	Do not ifconfig the TAP
  -tap-noconf
    	Do not send IP config with TAP ignore -subnet)
  -tap-persist
    	Set persist on TAP

**Comment by Doridian** [comment]
As I mentioned, auth is currently not supported in the server directly. Right now auth on the server side requires you to run a reverse proxy web server (such as nginx) to handle auth for you. That requires code to be added to the server.
It is supported in the client to authenticate to such a server.

**Comment by vochong** [comment]
When you have some time, can you please also add some basic authentication (e.g. preshared key) between the wsvpn cllient and wsvpn server, just to prevent others (without knowing the preshared key) from using the wsvpn server.   For example,  wsvpn server can run directly on an Internet facing OpenWrt router, not the more complicated scenario of being behind a reverse proxy.

**Comment by Doridian** [comment]
https://github.com/Doridian/wsvpn/releases/tag/1.1.0 adds HTTP basic auth support to the server, simply specify `-authenticator htpasswd` and put a `htpasswd` file into the working directory of the server. These follow the standard format of such files (you can either use a utility like `htpasswd` to create one for you, which uses secure password hashes, or you can hand-write them by putting `username:password` one per line into the file using any text editor)

**Comment by vochong** [comment]
Thanks so much Mark!   You're really fast in adding new features.

wsvpn (with TLS encryption, proxy, basic auth support) is now the most versatile and powerful VPN that can work in almost any network environment, even the most restrictive ones.  Thanks so much for an awesome program.
