### ISSUE TITLE
Add up and down scripts to server

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#33]
Please provide the script execution setting for WSVPN server.   Whenever any of the client tunnels is up or down, the server would automatically invoke the script, similar to the same capability on WSVPN client.

**Comment by Doridian** [comment]
Implemented in 3.11.
Same as with the client the script gets called with 3 arguments ([up/down] [ip with cidr] [interface name]). These arguments may be blank if unknown (the only known cause for this is a "down" event before the interface was fully configured)

**Comment by vochong** [comment]
"server --print-default-config" should show the scripts setting.

**Comment by Doridian** [comment]
Forgot about that, added to server default yml
