### ISSUE TITLE
How to build WSVPN binaries

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#34]
Hi Mark,
Can you give me some instructions on how to locally build WSVPN client and server binaries.  

I cloned your git project and ran ./build.sh but got the following errors.  

go version
go version go1.10.4 linux/amd64

$ ./build.sh 
go: unknown subcommand "mod"
Run 'go help' for usage.
Building for: windows / 386
client/config.go:4:2: cannot find package "embed" in any of:
	/usr/lib/go-1.10/src/embed (from $GOROOT)
	/home/python/go/src/embed (from $GOPATH)
client/config.go:9:2: cannot find package "github.com/Doridian/wsvpn/client/clients" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/client/clients (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/client/clients (from $GOPATH)
client/config.go:10:2: cannot find package "github.com/Doridian/wsvpn/shared" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/shared (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/shared (from $GOPATH)
client/config.go:11:2: cannot find package "github.com/Doridian/wsvpn/shared/cli" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/shared/cli (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/shared/cli (from $GOPATH)
server/config.go:4:2: cannot find package "embed" in any of:
	/usr/lib/go-1.10/src/embed (from $GOROOT)
	/home/python/go/src/embed (from $GOPATH)
server/main.go:11:2: cannot find package "github.com/Doridian/wsvpn/server/authenticators" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/server/authenticators (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/server/authenticators (from $GOPATH)
server/main.go:12:2: cannot find package "github.com/Doridian/wsvpn/server/macswitch" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/server/macswitch (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/server/macswitch (from $GOPATH)
server/config.go:8:2: cannot find package "github.com/Doridian/wsvpn/server/servers" in any of:
	/usr/lib/go-1.10/src/github.com/Doridian/wsvpn/server/servers (from $GOROOT)
	/home/python/go/src/github.com/Doridian/wsvpn/server/servers (from $GOPATH)

**Comment by Doridian** [comment]
WSVPN requires golang 1.18 (or higher) to build. Added that to documentation.

**Comment by vochong** [comment]
I upgraded golang to 1.18.4 and the build worked great   Thanks a lot.
