### ISSUE TITLE
HOW-TO: Tunnelling data over the VPN

### ISSUE THREAD

**Issue by Lime-Parallelogram** [Doridian/wsvpn#35]
Hi there, I love the premise of this application. I have been trying to set it up and I've managed to get a secure connection between my NAS and Laptop (both Linux). Despite having the tunnel interfaces set up on both server and client, I'm having trouble getting all of my packets sent through the VPN. 

If found this article (https://help.ubuntu.com/community/SSH_VPN - particularly the 'Plugging into the Network' bit) which talks about sending data over the tunnel interface. Despite this, it seems a bit old and outdated so I wondered if you had any advice on doing this - should I even need to do this or is it supposed to be automatic?

Many thanks,
Will

P.S. It took me quite a while to figure out how to set-up the mTLS authentication. I compiled a list of all the commands I used if you wish to review it and share it (below). 
```
#!/bin/sh
# ============== Change these settings ============== #
# Certificate Authority settings
CA_NAME="lp-personal-ca"
COUNTRY_CODE="UK"
COUNTY="Hertfordshire" # Or region
LOCAL="Harpenden"
ORGANISATION="Lime Parallelogram"

# Client settings
CLIENT_NAME="will-ZenBook"

# Server Keys
SERVER_NAME="vpnserver" # Should not include spaces

# Edit [alt_names] section in the following block. Add optional IP.1 attribute.
cat > $SERVER_NAME.v3.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
keyUsage = digitalSignature, nonRepudiation, keyEncipherment, dataEncipherment
subjectAltName = @alt_names

[alt_names]
DNS.1 = example.com
EOF

# ============== No more settings to change ============== #
echo "You will now have to choose a password. This will be required every time you attemp to sign a new certificate using your authority. You will need to enter it 5 times duting this process."
# Generate the private key that is used to sign new keys
openssl genrsa -aes256 -out $CA_NAME.key 4096

# Generate a certificate for the new CA
openssl req -x509 -new -nodes -key $CA_NAME.key -sha256 -days 1826 -out $CA_NAME.crt -subj "/CN=$CA_NAME CA/C=$COUNTRY_CODE/ST=$COUNTY/L=$LOCAL/O=$ORGANISATION"

## - server - ##
# Generate key and CSR for server
openssl req -new -nodes -out $SERVER_NAME.csr -newkey rsa:4096 -keyout $SERVER_NAME.key -subj "/CN=$SERVER_NAME /C=$COUNTRY_CODE/ST=$COUNTY/L=$LOCAL/O=$ORGANISATION"

# Create signed certificate for the server using the CSR
openssl x509 -req -in $SERVER_NAME.csr -CA $CA_NAME.crt -CAkey $CA_NAME.key -CAcreateserial -out $SERVER_NAME.crt -days 730 -sha256 -extfile $SERVER_NAME.v3.ext

## - client - ##
# Generate key and CSR for client
openssl req -new -nodes -out $CLIENT_NAME.csr -newkey rsa:4096 -keyout $CLIENT_NAME.key -subj "/CN=$CLIENT_NAME /C=$COUNTRY_CODE/ST=$COUNTY/L=$LOCAL/O=$ORGANISATION"

# Create signed certificate for the client using the CSR
openssl x509 -req -in $CLIENT_NAME.csr -CA $CA_NAME.crt -CAkey $CA_NAME.key -CAcreateserial -out $CLIENT_NAME.crt -days 730 -sha256

# Clean up uneccessary files
rm *.csr
rm *.v3.ext
```

**Comment by Doridian** [comment]
So, there is multiple ways a VPN can operate, WSVPN can do all 3, but, with different types of involvement:

a) Route only packets endpoint-to-endpoint or between all clients in the VPN, but never actually beyond the scope of the VPN itself. So you would run the server on your NAS, the client on a computer, and then use the NAS's VPN internal IP to connect to it (not the "real" IP, but the IP that is assigned to the server on its VPN interface, by default the subnet is 192.168.3.0/24, so the IP of the server would be 192.168.3.1).

b) Route everything through the VPN. WSVPN supports this with the `set-default-gateway` setting in the client's YML, such as:
```
tunnel:
  set-default-gateway: true
```

c) Route only specific "foreign" nets through the VPN. WSVPN supports this using up and down scripts only currently. Something like a script running `ip route add 10.1.2.0/24 dev $2`
This is what the "Plugging into the network" manual suggests. You can do that manually or use an `up` script on the client.
Technically the protocol supports pushing specific routes to the client, but I have not implemented an option for the server to send such requests, yet.

If you need help figuring out which config options exist, you can always run the server or client with `--print-default-config`

Let me know if you have any more questions or anything I explained is unclear.


As for the mTLS bit, yeah, I tend to use that feature with an external CA and not shell scripts just for making it easier to manage.

**Comment by Lime-Parallelogram** [comment]
Amazing, thanks for the quick response, what I really want is option 2. I tried enabling the set-default-gateway setting but for some reason the connection just wouldn't stick. I've attached the output logs below from both the server and the client - any suggestions. I tried increasing the ping timeout but this didn't seem to help 😢.

### Output
Client
```
2022/07/29 22:09:52 Local version is: 3.11.1 (protocol 11)
2022/07/29 22:09:52 base.go:94: [CLIENT-UNSET] Connecting to wss://vpn.limeparallelogram.uk with authentications: mTLS
2022/07/29 22:09:53 connection.go:55: [CLIENT-UNSET] Command serialization: json
2022/07/29 22:09:53 connection.go:59: [CLIENT-UNSET] TLS 1.3 WebSocket connection established with cipher=TLS_AES_128_GCM_SHA256
2022/07/29 22:09:53 ping.go:48: [CLIENT-UNSET] Ping enabled with interval 30s and timeout 5s
2022/07/29 22:09:53 commands.go:60: [CLIENT-UNSET] Remote version is: 3.11.1 (protocol 11)
2022/07/29 22:09:53 commands.go:75: [CLIENT-UNSET] Got reply to command ID 2fc7382d-1bfd-4c91-aa06-b276c94a9ea7 (ok): OK
2022/07/29 22:09:53 base.go:102: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Setting fragmentation: enabled
2022/07/29 22:09:53 commands.go:60: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Network mode TUN, Subnet 192.168.3.2/24, MTU 1420, IPConfig enabled
2022/07/29 22:09:53 commands.go:76: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Opened wsvpn-tun
2022/07/29 22:09:53 commands.go:89: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Configured interface, starting operations
2022/07/29 22:10:23 ping.go:32: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Sent ping
2022/07/29 22:10:28 ping.go:40: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Ping timeout
2022/07/29 22:10:28 vpnnet.go:37: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Error reading packet from tun: read tun: file already closed
2022/07/29 22:10:28 base.go:62: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Automatic reconnection disabled, exiting!
```

Server
```2022/07/29 21:09:53 sockets.go:45: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] TLS 1.3 connection established with cipher=TLS_AES_128_GCM_SHA256

2022/07/29 21:09:53 sockets.go:94: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Upgraded connection to WebSocket

2022/07/29 21:09:53 sockets.go:126: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Assigned interface wsvpn0

2022/07/29 21:09:53 sockets.go:135: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Command serialization: json

2022/07/29 21:09:53 sockets.go:153: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Connection fully established

2022/07/29 21:09:53 ping.go:48: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Ping enabled with interval 30s and timeout 5s

2022/07/29 21:09:53 commands.go:60: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Remote version is: 3.11.1 (protocol 11)

2022/07/29 21:09:53 base.go:102: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Setting fragmentation: enabled

2022/07/29 21:09:53 commands.go:75: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Got reply to command ID 76fceae1-9b97-4a31-af08-875db727bdd3 (ok): OK

2022/07/29 21:10:23 ping.go:32: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Sent ping

2022/07/29 21:10:28 ping.go:40: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Ping timeout

2022/07/29 21:10:28 vpnnet.go:37: [CLIENT-8ad6e52b-e0ed-427d-acbf-5c5dfc9f810b] Error reading packet from tun: read tun: file already closed
```

**Comment by Doridian** [comment]
Ah, I think I know what's going on here.
I suspect the VPN tries to talk to the server over the VPN which of course does not work.
Most VPNs solve this by creating a route specifically for the VPN server endpoint to use the normal interface (and not the VPN).

For now you could do this manually (on the client machine) using, for example: `ip route add 1.2.3.4 via <your router's IP>` and possibly also `ip route add <your router's IP> dev <your network interface>`.
Let me know which of those two you need, or both (or if neither helps).

**Comment by Lime-Parallelogram** [comment]
Thanks again for the response, I used the rule `sudo ip route add <external home ip> via <router ip>` and that allowed the VPN to connect and ping-pong properly. Unfortunately I now have another problem, all of my traffic is being sent through the VPN but none of it (apart from traffic destined for the NAS itself) is receiving responses.
In that article I sent from the Ubuntu Wiki, it talked about modifying the ARP table on the server but the `arp` command is now deprecated so I'm not sure what the correct way to do it now is.

**Comment by Doridian** [comment]
Did you on the NAS set it up "as a router"?

If you need help with that type of configuration, the guide below seems to be fairly accurate (the sysctl, the MASQUERADE rules and the FORWARD rules all 3 are important):
https://dannyda.com/2020/04/26/how-to-use-configure-set-iptables-to-allow-nat-masquerade-nat-masquerading-net-ipv4-ip_forward/
They mention a specific interface to allow forwarding for (iptables -A FORWARD ... lines).
You can for testing bypass that entire thing by just allowing all forward traffic (iptables -A FORWARD -j ACCEPT), and using an "up" script on the server to allow these rules dynamically when you've verified it works if you wish.

**Comment by Lime-Parallelogram** [comment]
Right, I got it working running the server on a fresh install of debian using only the following two commands:
``` iptables -t nat -A POSTROUTING -s 192.168.3.0/24 -j MASQUERADE``` and ```sudo sysctl -w net.ipv4.ip_forward=1``` (using guide https://aboullaite.me/kvm-qemo-forward-ports-with-iptables/). I can't quite get it running on my NAS yet but I'm guessing its because of all the other firewall rules that it has for things like docker and libvirt. I'll keep you posted.

**Comment by Doridian** [comment]
If you run Docker anyway, might be easier to run the VPN inside of docker. Should be fairly similar to how you run OpenVPN in Docker (some privileges/capabilities need to be added, the appropriate sysctl/iptables rules, etc).
Never tried, so I don't know how true that statement is precisely, but, might be worth a try if you can't get going otherwise.
