### ISSUE TITLE
[Question]WSVPN can't pass OSPF and BFD messages?

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#365]
Server Side,and IP is 10.100.0.1
Client Side,and IP is 10.100.0.2
Server Side tcpdump pic:
![image](https://github.com/Doridian/wsvpn/assets/13675031/8db6bdd9-0feb-47c1-aa62-c3bb452044e9)
Client Side tcpdump pic:
![image](https://github.com/Doridian/wsvpn/assets/13675031/04834250-8274-4730-9c4c-f7580348e552)

**Comment by Handsome1080P** [comment]
My MTU set 1380.
![image](https://github.com/Doridian/wsvpn/assets/13675031/6c3cf3d1-efd4-476d-8eaf-64dc4f8cbe9d)
![image](https://github.com/Doridian/wsvpn/assets/13675031/796ac6f0-8068-45dd-bc8c-5fd50fc62d38)
![image](https://github.com/Doridian/wsvpn/assets/13675031/357a78c8-ca98-4f1d-b6f0-a15bb1c6064b)
No bfd or ospf sessions online.

**Comment by Handsome1080P** [comment]
Server config:
![image](https://github.com/Doridian/wsvpn/assets/13675031/14a246f9-bf3e-4b1d-ab89-a74ea5b4f3af)

**Comment by Handsome1080P** [comment]
another config,still can't connect.
![image](https://github.com/Doridian/wsvpn/assets/13675031/ee83082f-dfa3-49f3-bb7d-460eebf33cef)

**Comment by Doridian** [comment]
The fact that the packets appear in both the server AND the client means the packets are passing successfully at least partially.
The issue is likely OSPF/BFD use multicasting (at least OSPF does), so you will need to switch to a "TAP" interface, not "TUN" (switch mode to `TAP` on the server config and change all interface names from `tunX` to `tapX`)

**Comment by Handsome1080P** [comment]
> The fact that the packets appear in both the server AND the client means the packets are passing successfully at least partially. The issue is likely OSPF/BFD use multicasting (at least OSPF does), so you will need to switch to a "TAP" interface, not "TUN" (switch mode to `TAP` on the server config and change all interface names from `tunX` to `tapX`)
> 
> Also I should note I have not tested broadcast/multicast traffic in WSVPN, so it might not pass even in TAP mode (but I can fix that, TUN mode is effectively incapable of transmitting anything that isn't a unicast IP packet)

I already set connection type use PTP.maybe I need set to PTMP and TAP mode for wsvpn.

**Comment by Handsome1080P** [comment]
NEW server config.I changed mode to Layer2 TAP.still can't get BFD up.I have checked normal connection on Wireguard.Server and client will send message to each others but in WSVPN tunnel I only got client(10.100.0.2) to server(10.100.0.1).Server no response.
This is server config:
![image](https://github.com/Doridian/wsvpn/assets/13675031/a00cf428-601b-4bff-b744-3b736d543d3a)
BIRD2 Server BFD status:
![image](https://github.com/Doridian/wsvpn/assets/13675031/29b494da-5f98-42fa-b027-1bfe805acde9)
BIRD2 Client BFD status:
![image](https://github.com/Doridian/wsvpn/assets/13675031/caae4ace-1d8c-46ea-9907-3791cd55ad0b)
TCPDump on Server for WSVPN:
![image](https://github.com/Doridian/wsvpn/assets/13675031/52917e84-807d-4bf8-99a7-c3cd088a8f05)
TCPDump on Client for WSVPN:
![image](https://github.com/Doridian/wsvpn/assets/13675031/85899956-d288-4b84-85df-db19ee89863a)
TCPDump on Server for Wireguard:
![image](https://github.com/Doridian/wsvpn/assets/13675031/1fedfbf3-f4be-4c86-a350-ba0b2570b77f)
TCPDump on Client for Wireguard:
![image](https://github.com/Doridian/wsvpn/assets/13675031/63b15701-4c95-4c9a-ad62-e278687e35de)

**Comment by Handsome1080P** [comment]
if u can,plz fix this.Thx a lot.

**Comment by Handsome1080P** [comment]
additional,OSPF is working.only BFD I have no ideal.I removed my OSPF'BFD configration,now OSFP connected.
![image](https://github.com/Doridian/wsvpn/assets/13675031/de672964-843f-4366-926e-e695b6b7f788)
![image](https://github.com/Doridian/wsvpn/assets/13675031/bd77c6c0-3c12-4a23-867f-dc694c2113c2)

**Comment by Handsome1080P** [comment]
BFD config,client use same as this.
![image](https://github.com/Doridian/wsvpn/assets/13675031/8f0525ce-6054-41e1-a016-b0686ccabd6f)

**Comment by Handsome1080P** [comment]
WSVPN TUN mode can't forward IP traffic.OSPF connected by can't forward data.
