### ISSUE TITLE
SSLKEYLOGFILE?

### ISSUE THREAD

**Issue by nemethf** [Doridian/wsvpn#39]
Is it possible to start the server/client so that it writes its secrets into a KeyLog file?  

I've searched the project source files quickly and I'm guessing the answer is no.  In that case, can you, please, add this functionality?  I'm not really familiar with go and I'm guessing once again that [this](https://github.com/lucas-clemente/quic-go/blob/6511723c282ad479ef096f587d8f5fcc125a5562/interop/server/main.go#L29-L36) and [this](https://github.com/lucas-clemente/quic-go/blob/6511723c282ad479ef096f587d8f5fcc125a5562/interop/server/main.go#L57) probably show how this can be done.

Thank you.

**Comment by Doridian** [comment]
This is an interesting feature request to say the least.
I will check into your suggestions after work today, doesn't seem too hard.

Out of curiosity, what is your use-case for these options?

**Comment by nemethf** [comment]
We'd like to study the webtransport protocol and there seems to be only a handful of applications currently available.  On the one hand, we're interested to see the details of the connection setup and I'm not able to dissect QUIC packets in Wireshark without this feature.  Wsvpn is also ideal because we can easily measure the performance of bulk transfer.  Thanks again.

**Comment by Doridian** [comment]
I have added the feature in 3.13.0.
It is available in both client and server using `client/server -> tls -> config -> key-log-file` in the respective YAML.

The log file will be created to be only owner-accessible (so, for most cases, root) to mitigate the security issues as much as possible.
Whenever this option is used, a warning will also be printed to reduce the risk of accidental use.
