### ISSUE TITLE
Does wsvpn have its own encryption?

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#4]
I don't know golang but from a quick look at the code, it looks like wsvpn does not provide its own encryption and users are supposed to have their own application encryption (e.g ssh etc.) for the traffic flowing through it.   Is it correct?   Thanks a lot.

**Comment by Doridian** [comment]
@vochong As wsvpn relies on HTTP, it can use standard TLS for encryption (just provide a certificate and private key to the server, see `tls-cert` and `tls-key` arguments for the server)

**Comment by vochong** [comment]
I don't see the tlc-cert and tls-key arguments for the server:

./server-linux-amd64 -h
Usage of ./server-linux-amd64:
  -client-to-client
    	Allow client-to-client communication (in TAP)
  -listen string
    	Listen address for the WebSocket interface (default "127.0.0.1:9000")
  -mtu int
    	MTU for the tunnel (default 1280)
  -subnet string
    	Subnet for the tunnel clients (default "192.168.3.0/24")
  -tap
    	Use a TAP and not a TUN
  -tap-iface-noconf
    	Do not configure TAP interface at all except MTU
  -tap-name string
    	Use specific TAP name
  -tap-no-ifconfig
    	Do not ifconfig the TAP
  -tap-noconf
    	Do not send IP config with TAP ignore -subnet)
  -tap-persist
    	Set persist on TAP

**Comment by vochong** [comment]
Oops, I was using your older server binary and it did not have the tls-cert and tls-key options.   I've just downloaded your newest server binary and it has these options now.   Thanks so much for a great program.

./server-linux-amd64 -h
Usage of ./server-linux-amd64:
  -client-to-client
    	Allow client-to-client communication (in TAP)
  -listen string
    	Listen address for the WebSocket interface (default "127.0.0.1:9000")
  -mtu int
    	MTU for the tunnel (default 1280)
  -subnet string
    	Subnet for the tunnel clients (default "192.168.3.0/24")
  -tap
    	Use a TAP and not a TUN
  -tap-iface-noconf
    	Do not configure TAP interface at all except MTU
  -tap-name string
    	Use specific TAP name
  -tap-no-ifconfig
    	Do not ifconfig the TAP
  -tap-noconf
    	Do not send IP config with TAP ignore -subnet)
  -tap-persist
    	Set persist on TAP
  -tls-cert string
    	TLS certificate file for listener
  -tls-key string
    	TLS key file for listener
