### ISSUE TITLE
HTTP Proxy support?

### ISSUE THREAD

**Issue by eidyev** [Doridian/wsvpn#402]
How can I use the VPN if my internet connection is through an http proxy server (squid 4)

**Comment by Doridian** [comment]
In case you need to manually specify the proxy, you need to set the `client.proxy` option, see example config here: https://github.com/Doridian/wsvpn/blob/main/client/cli/client.example.yml#L25

In case of a transparent proxy, it should just work.

In case it does not work the most likely culprit is that the proxy does not support WebSocket (or, possibly, the CONNECT method for raw TCP connections in case of TLS etc), in which case WSVPN can not function.

**Comment by eidyev** [comment]
In my case, the proxy I use does support the connect method and allows https and websocket connections.

I am sysadmin, is there a detailed guide to install a server for this VPN on Linux and install and configure a client on another PC to test it?

**Comment by Doridian** [comment]
Sounds good, I've never gotten to writing some good docs, beyond the example configs ( https://github.com/Doridian/wsvpn/blob/main/client/cli/client.example.yml and https://github.com/Doridian/wsvpn/blob/main/client/cli/client.example.yml ).

And some very basic example setups here: https://github.com/Doridian/wsvpn/wiki/Example:-VPN-with-TLS-and-htpasswd-authentication.

All you have to do is download the compiles binaries (or compile yourself), and then run the VPN server's binary. It does not ship as packages or service files by default.

**Comment by eidyev** [comment]
And is there a video tutorial on YouTube or another platform that shows how to try it?

**Comment by Doridian** [comment]
None I would be aware of at this time.

**Comment by eidyev** [comment]
Do you have a real-time chat where we can talk better, Telegram?
