### ISSUE TITLE
Enhancement request: create a single binary that can run either as client or server depending on the command flag.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#44]
I have some complicated network scenarios in which I need to run both wsvpn client and server on the same device.  Since embedded devices may have very little flash storage,  it would be great if we can have a single binary that can run as either a client or server.   That will reduce the storage space.

binary --client  or  --server

**Comment by Doridian** [comment]
3.15.0 should be what you're looking for
`--side=client` and `--side=server` in the "dual" binary

**Comment by vochong** [comment]
You're truly amazing!  Thanks so much.

From 19 MB for both client/server binaries (non-static builds), now a single dual image (with compression) is only 2.8 MB.  Hurrah!

**Comment by vochong** [comment]
I've also noticed that that I can now use the latest Go 1.19 to build your WSVPN.   In the previous version, I had to all back to Go 1.18.5 to compile it.

**Comment by Doridian** [comment]
Yeah it got contributed in this PR https://github.com/Doridian/wsvpn/pull/40

I didn’t realize 1.19 was out as my package manager has not got that release yet

**Comment by Doridian** [comment]
I added another output to the releases for scenarios where you are space constrained.
All release Linux binaries now get a `-compressed` variant which is packed with UPX at max compression level.
This reduces the binary sizes to around 3MB. (Which, from the sizes you report, might have been what you already did)
