### ISSUE TITLE
one-interface-per-connection Option Enabled,interface up but got a error in log.

### ISSUE THREAD

**Issue by Handsome1080P** [Doridian/wsvpn#450]
> 2024/01/15 09:35:50 sockets.go:128: [CLIENT-a6de0358-0add-4293-8dc9-847c310d1032] Command serialization: json
2024/01/15 09:35:50 sockets.go:159: [CLIENT-a6de0358-0add-4293-8dc9-847c310d1032] Assigned interface ws0
RTNETLINK answers: File exists
2024/01/15 09:35:50 Error adding peer route 192.168.222.2 for ws0: command ip route add 192.168.222.2/32 dev ws0: exit status 2
![image](https://github.com/Doridian/wsvpn/assets/13675031/17c89dba-9846-49a2-91ef-32281ba3e99d)

**Comment by Handsome1080P** [comment]
interface up and the route already include,not need IP command set it again.

**Comment by Handsome1080P** [comment]
route already set,this error seems a bug?
![image](https://github.com/Doridian/wsvpn/assets/13675031/695295f3-f750-4295-9f7d-6e33fe68432f)

**Comment by Doridian** [comment]
@Handsome1080P These errors happen and are normal. It is WSVPN just "making sure" the route exists, but Linux will add it automatically as well for the local-subnet route.
