### ISSUE TITLE
build.py traceback

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#46]
$ ./build.py 
Starting: Go build client-linux-amd64
Starting: Go build client-linux-386
Starting: Go build client-linux-arm64
Starting: Go build client-linux-arm32v5
Done: Go build client-linux-arm64
Starting: Go build client-linux-arm32v6
Done: Go build client-linux-amd64
Starting: Go build client-linux-arm32v7
Done: Go build client-linux-386
Starting: Go build client-linux-mips
Done: Go build client-linux-arm32v5
Starting: Go build client-linux-mips-softfloat
Done: Go build client-linux-arm32v6
Starting: Go build client-linux-mipsle
Done: Go build client-linux-mips
Starting: Go build client-linux-mipsle-softfloat
Done: Go build client-linux-arm32v7
Starting: Go build client-linux-mips64
Done: Go build client-linux-mips-softfloat
Starting: Go build client-linux-mips64le
Done: Go build client-linux-mipsle-softfloat
Done: Go build client-linux-mipsle
Starting: Go build client-darwin-amd64
Done: Go build client-linux-mips64le
Starting: Go build client-darwin-arm64
Starting: Go build client-windows-amd64.exe
Done: Go build client-linux-mips64
Starting: Go build client-windows-386.exe
Done: Go build client-darwin-amd64
Starting: Go build client-windows-arm64.exe
Done: Go build client-windows-amd64.exe
Starting: Go build server-linux-amd64
Done: Go build client-windows-386.exe
Starting: Go build server-linux-386
Done: Go build client-darwin-arm64
Starting: Lipo
Done: Lipo
Starting: Go build server-linux-arm64
Done: Go build client-windows-arm64.exe
Starting: Go build server-linux-arm32v5
Done: Go build server-linux-amd64
Starting: Go build server-linux-arm32v6
Done: Go build server-linux-386
Starting: Go build server-linux-arm32v7
Done: Go build server-linux-arm64
Starting: Go build server-linux-mips
Done: Go build server-linux-arm32v5
Starting: Go build server-linux-mips-softfloat
Done: Go build server-linux-arm32v7
Starting: Go build server-linux-mipsle
Done: Go build server-linux-arm32v6
Starting: Go build server-linux-mipsle-softfloat
Done: Go build server-linux-mips
Starting: Go build server-linux-mips64
Done: Go build server-linux-mips-softfloat
Starting: Go build server-linux-mips64le
Done: Go build server-linux-mipsle
Starting: Go build server-darwin-amd64
Done: Go build server-linux-mipsle-softfloat
Starting: Go build server-darwin-arm64
Done: Go build server-linux-mips64
Starting: Go build server-windows-amd64.exe
Done: Go build server-linux-mips64le
Starting: Go build server-windows-386.exe
Done: Go build server-windows-amd64.exe
Starting: Go build server-windows-arm64.exe
Done: Go build server-darwin-amd64
Starting: Go build dual-linux-amd64
Done: Go build server-darwin-arm64
Starting: Lipo
Done: Lipo
Starting: Go build dual-linux-386
Done: Go build server-windows-386.exe
Starting: Go build dual-linux-arm64
Done: Go build server-windows-arm64.exe
Starting: Go build dual-linux-arm32v5
Done: Go build dual-linux-386
Starting: Go build dual-linux-arm32v6
Done: Go build dual-linux-arm64
Starting: Go build dual-linux-arm32v7
Done: Go build dual-linux-amd64
Starting: Go build dual-linux-mips
Done: Go build dual-linux-arm32v5
Starting: Go build dual-linux-mips-softfloat
Done: Go build dual-linux-arm32v6
Starting: Go build dual-linux-mipsle
Done: Go build dual-linux-arm32v7
Done: Go build dual-linux-mips
Starting: Go build dual-linux-mipsle-softfloat
Done: Go build dual-linux-mips-softfloat
Starting: Go build dual-linux-mips64
Starting: Go build dual-linux-mips64le
Done: Go build dual-linux-mipsle
Starting: Go build dual-darwin-amd64
Done: Go build dual-linux-mipsle-softfloat
Starting: Go build dual-darwin-arm64
Done: Go build dual-linux-mips64
Starting: Go build dual-windows-amd64.exe
Done: Go build dual-linux-mips64le
Starting: Go build dual-windows-386.exe
Done: Go build dual-darwin-amd64
Starting: Go build dual-windows-arm64.exe
Done: Go build dual-windows-amd64.exe
Done: Go build dual-windows-386.exe
Done: Go build dual-darwin-arm64
Starting: Lipo
Done: Lipo
Traceback (most recent call last):
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 337, in <module>
    main()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 331, in main
    task.join()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 137, in join
    raise self.exc
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 125, in run
    self._run()
  File "/home/python/Venv/WSVPN/wsvpn/./build.py", line 227, in _run
    check_call(args)
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1720, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Done: Go build dual-windows-arm64.exe

**Comment by Doridian** [comment]
Ah, you don't have a version of lipo which is needed for universal binaries on macOS.
Pushed a commit that makes the lipo step opt-in via a flag. (`./build.py --help` for all flags)
