### ISSUE TITLE
Using a single TUN interface for all clients takes away the routing flexibility of WSVPN server

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#47]
The power of WSVPN comes from its extreme flexibility and security.   Forcing the server to use a single TUN interface for all clients takes away all the routing flexibility on the server itself.  It also takes away the ability to quickly know how many clients are connected.

Please add the option to use single TUN or multiple TUN on the server.   Thanks a lot.

**Comment by Doridian** [comment]
Can you elaborate on routing flexibility?
Considering there is no way to predict which client uses which TUN, what do you gain over the current implementation?
You still have control over whether clients can talk to other clients (`allow-client-to-client`)

**Comment by vochong** [comment]
The up/down script can probe the clients and add/remove routes (e.g. to networks behind each client) accordingly.

Having the individual TUN interface allows us to track each client's RX/TX traffic metrics.

**Comment by Doridian** [comment]
I have just pushed 4.1.0. This adds an option `one-interface-per-connection` to the `interface` section.
This can be used for both TUN (which restores the old TUN behaviour) as well as TAP.
This changes the meaning of `interface -> name` to be a prefix (like the old `name-prefix` option).

With your use-case I have a new idea of what might be useful: If authentication is enabled, pass the username / mTLS name to the script. Would that be useful to you?

**Comment by vochong** [comment]
Hi Mark,

The new change (one-interface-per-connection) works great.

Yes, your idea of passing the username/mTLS name to the script is awesome.  That would make things even much more flexible.  

Thanks so much for creating and continuously improving this wonderful software.
