### ISSUE TITLE
Pass authenticated username to up and down script on server

### ISSUE THREAD

**Issue by Doridian** [Doridian/wsvpn#48]
If auth is enabled as a new argument

**Comment by Doridian** [comment]
Fixed in 4.2.0

**Comment by vochong** [comment]
Can you please give a small script snippet that explains the usage of the new auth user argument.  I tried to use it in the script but it did not seem work.  Thanks.

**Comment by Doridian** [comment]
I just pushed 4.2.1 as I noticed a bug I introduced in 4.2.0 with scripts, which would cause an argument to just be missing entirely on the script.

So probably on 4.2.1 your script will just work as is.

However, for a simple bash script example that works now (4.2.1):
```
#!/bin/sh
OP="$1"
IP="$2"
IFACE="$3"
USER="$4"
echo "Hello, $USER"
```

**Comment by vochong** [comment]
The script works fine with auth user argument using the new version 4.2.1.  Thanks a lot Mark.

You're an incredible engineer.   You pinpoint the bugs and fix them at at the speed of light :-)
