### ISSUE TITLE
wsvpn binary for armv7l

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#5]
Hi Mark,

Could you please also build wsvpn binary for armv7l.   Lots of modern OpenWrt routers are armv7l, and RPI2/3/4 (with 32-bit Linux) is also armv7l.   Thanks a ton!

**Comment by Doridian** [comment]
Just pushed 1.1.1 which includes support for more architectures. The one you are looking for is what golang calls just `arm`
