### ISSUE TITLE
Web API for WSVPN server

### ISSUE THREAD

**Issue by nemethf** [Doridian/wsvpn#58]
I wondered about using webtransport in wsvpn as it seems the underlying quic protocol is capable to provide everything wsvpn requires  from webtransport.   However, http3 allows wsvpn to handle endpoints differently.  For example, https://server.example.com:9000/ could return a webpage  containing the current usage statistics and https://server.example.com:9000/vpn could be used to create a connection.  Although, this feature might not be that useful.  What do you think?  Thank you.

**Comment by Doridian** [comment]
I was in fact thinking about adding a management/statistics interface.

However, while it is possible to put these on the same port (and, in fact, the same path even!), it seems like in the common use cases, people might want to add different protections for both (maybe put the management/stats behind a firewall).

So, I would be more inclined to add a separate listener that is opt-in that can do these things (say, expose a very basic REST API that can both show statistics about the server and connected clients, as well as kick clients out of the server)
