### ISSUE TITLE
Tunnel number is not appended to the tunnel interface prefix when one-interface-per-connection is set to True.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#67]
Server config:
  name: "wsserver"
  one-interface-per-connection: true

It's supposed to be wsserver0 instead of wsserver  (seen when using wsvpn 5.6.1)

ifconfig 
  wsserver  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00

**Comment by Doridian** [comment]
Fixed in 5.6.2

**Comment by vochong** [comment]
Thanks a lot.  It works now.
