### ISSUE TITLE
Basic authentication (htpasswd) fails with the error ":websocket: bad handshake" for secure password hash.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#7]
Hi Mark,

If the htpasswd file contains clear-text password (e.g. wsvpn:user), basic authentication using htpasswd works and wsvpn tunnel is established.

If the htpasswd file contains secure password hash (created using htpasswd command),  basic authentication using htpasswd always fails with the error "panic: websocket: bad handshake" shown on the client side.

# the same htpasswd file is saved on server and client
cat htpasswd
wsvpn:$apr1$XU7CFUAq$qHS6n7DDMZxrx4I77FfKD0

SERVER
sudo ./server-linux-arm -authenticator htpasswd  -listen 192.168.1.1:9000
2022/06/10 05:25:55 [S] VPN server online at 192.168.1.1:9000, mode TUN, serving subnet 192.168.3.0/24 (253 max clients) with MTU 1280

CLIENT
sudo ./client-linux-amd64 -auth-file htpasswd -proxy http://http:proxy@192.168.1.10:8080 -connect ws://192.168.1.1:9000 
2022/06/09 22:27:07 Connecting to ws://192.168.1.1:9000 as user wsvpn
2022/06/09 22:27:07 Using HTTP proxy http://http:xxxxx@192.168.1.10:8080
panic: websocket: bad handshake

goroutine 1 [running]:
main.main()
	/home/runner/work/wsvpn/wsvpn/client/main.go:110 +0x9de

**Comment by Doridian** [comment]
@vochong If you use a hashed secure password, that file will not work on the client.
The client always needs a plaintext file (a single line of user:password) due to how Basic authentication functions.

**Comment by vochong** [comment]
Awesome support!  It works according to your instruction.

Stupid me.  Hash is a one-way function so the client must know the original password, not the hash.   Server receives the client's password and hashes it to check whether it matches the user's stored secure password hash.
