### ISSUE TITLE
Add option on WSVPN client to validate server TLS certificate against specified signer/CA

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#8]
Hi Mark,

Currently,  the wsvpn client only validates the wsvpn server using its IP SAN attribute in its TLS certificate.  The IP SAN attribute can always be fabricated in the server's TLS certificate.

I believe wsvpn client should definitely be enhanced to support the validation of the server's certificate using its signing ca certificate.  That would render wsvpn much better from a security point of view.   Without it, an adversary can always wage a MITM attack by setting the -authenticator allow-all to defeat the basic authentication.

Example of the new option:

wsvpn-client 
   -signing-ca-cert
            Signing CA certificate of the server's TLS certificate

**Comment by Doridian** [comment]
It should validate the certificate against your local trust store (the same one, say, your web browser might use).
I will rename this issue to specify a specific issuer to accept for hardened security reasons, and so you can use your own self-made CA if desired.

**Comment by vochong** [comment]
Thank you so much!  You're simply amazing.

**Comment by Doridian** [comment]
Version 1.2.0 adds this as a new feature. You can specify the `--ca-certificates` argument. This file can contain one or more PEM encoded certificates the client should trust as CAs/roots (if this is specified, the client will not load the system trust store at all and only trust the specified certificates)
