### ISSUE TITLE
WSVPN server may not get the client's new IP address when the client re-connects automatically to server after an error.

### ISSUE THREAD

**Issue by vochong** [Doridian/wsvpn#99]
If the client reconnects to the server after an error (connection lost, proxy down and then up etc.) and *gets a new IP address after the successful re-connection*, the server may not correctly get the client's new IP address.  This causes the server script to fail to set the route to the networks behind the client.

Can you please check the code to see if such condition may exist in some corner case (WSVPN 5.12.2 for server/client)

**Comment by Doridian** [comment]
It would be much appreciates if you could provide logs for client and server in such a case.
I can go searching for myself, but logs would help a lot.

**Comment by vochong** [comment]
Sorry, since WSVPN has been working so well so far,  I redirected the server and client's output to /dev/null so I did not have any log.   Normally, if the client reconnected, it got the same IP address it was using before the error so I never saw the problem.  Today I lost the connection to the networks behind the client and found that tun interface was still up in the server,  but all the routes were not created by the server script for the "up" condition.  After connecting to the client, I found that the tun interface was also up on the client, but its IP address changed to a new one (e.g.  from the usual 192.168.11.2 to 192.168.11.3).

**Comment by Doridian** [comment]
I assume what happened is the server for some reason did not tear down the TUN, because it did not see the client go away, but then for some reason re-used it but still assigned the client a new IP.
That is very odd, but not impossible.

**Comment by Doridian** [comment]
I just checked and that should not be possible to happen.

However, what is very possible to happen, is desynchronized timeouts (which I really can't do much about).

So initially the client connects to the server, this casues `UP tun0 1.2.3.4 username` to happen.
Essentially, the connection between the server and client is disrupted.
Now, the client notices this first, and attempts a reconnect.
The server takes longer to notice the disconnect and keeps the client interface alive.
The client now reconnects and gets a new ip, this causes `UP tun1 1.2.3.5 username` to happen.
Now, the server notices the old client is actually gone, so this causes `DOWN tun0 1.2.3.4 username` to happen.

If your up/down scripts somehow depend on the fact a user can only be connected once, this might cause state issues (considering you get a DOWN event for the user after the UP event without the connection being gone).
If this sounds like it could be an issue in your setup, let me know.
But, if that's it, the only real fix is (on your end) tracking which interface a user is on (which might be multiple).

At least, until https://github.com/Doridian/wsvpn/issues/52 is implemented and can prevent a user from connecting multiple times (such as by killing old connections or preventing new ones)

**Comment by vochong** [comment]
Yes, the server up script attempts to add a certain set of routes when a specific user is matched.

**Comment by Doridian** [comment]
In that case, the only way to fix it would be to keep track of which interface a client had latest (Say, write it to a file like `USERNAME.iface`), and only if the `DOWN` callback has that interface, it gets processed.

(Again, until #52)

**Comment by vochong** [comment]
Thanks a lot. You're very sharp.

**Comment by Doridian** [comment]
#52 is now fixed, so I'll consider this issue closed. Feel free to re-open if you have more questions.
